xen-troops/moulin

docs/about.rst

Moulin now have pygit2 in dependencies list. But it appears that in
some cases (like when using Ubuntu 18.04) pip/pip3 can't install
pygit2 from own repository because pygit2 depends on exact version of
libgit2. Which is provided by distro.
Signed-off-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>

doc: add information about pygit2 requirements

---

moulin/build_generator.py

To generate list of dependencies from fetched sources, we need
to fetch sources first.
Signed-off-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>

build_generator: make dyndep target depend on sources

---

moulin/build_generator.py
moulin/builders/android.py
moulin/builders/yocto.py
moulin/make_syntax.py
moulin/utils.py

Ninja supports two ways to discover dynamic dependencies:
- dyndep mechanism - it is used to discover mandatory dependencies
*before* build
- deps mechanism - it is used to discover optional dependencies
*during* build. It is used mostly to track dependencies between
C source files and header files they include
Prior to this patch, Moulin used the dyndep mechanism. But it appears
that it does not cope will with removing or renaming files. As those
type of dependencies are mandatory, Ninja will complain that it does
not know how to build removed file.
So, only one way to fix this is to move to "deps" mechanism. This is
exactly what this patch does.

Switch to "deps" dependency tracking mechanism

---

docs/user-reference.rst
moulin/builders/yocto.py

In some cases additional layers are not needed. Skip layers adding if
none specified.
Signed-off-by: Mykyta Poturai <mykyta_poturai@epam.com>

builders: yocto: Make layers optional

---

docs/user-reference.rst
moulin/builders/android.py

This works in the same way as Yocto. Paths are relative to component
build directory.
Signed-off-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>

builders: android: add support for additional_deps property

---

docs/about.rst

Only version 1.10+ supports multiple outputs.

doc: Add ninja 1.10+ to requirements

---

moulin/fetchers/git.py

If $git_url uses ssh protocol and is not in .ssh/known_hosts,
the ssh client starts to iterate with a user.
But this interaction is not visible and looks
just like the ninja hung on some operation.
So we have to use ssh in BatchMode to throw
an error instead of asking invisible questions.

fetchers: git: Use ssh in batch mode

---

docs/rouge.rst
moulin/rouge/block_entry.py
moulin/rouge/ext_utils.py

Add new class for creating vfat filesystem with files. Move the common
code between ext4 and vfat classes to the new base class "FileSystem".
Signed-off-by: Mykyta Poturai <mykyta_poturai@epam.com>

rouge: Add vfat filesystem support

---

docs/rouge.rst
moulin/rouge/block_entry.py
moulin/rouge/sfdisk.py

gpt_uuid parameter is intendend to set UUID for gpt partitions. Partition UUID can be used to mount partition from fstab regardless of the storage type.

Introducing new parameter to rouge: gpt_uuid

---

moulin/rouge/sfdisk.py

Do not add 1 additional sector to the end of each partition, as this
would unnecessarily add space between partitions that are already
aligned to DEFAULT_ALIGNMENT. Selection of 'next sector' is already
done by start + size calculation.
This avoids wasting space and allows to align the first partition
exactly to DEFAULT_ALIGNMENT (and not to DEFAULT_ALIGNMENT + 2048,
as it is now).
Signed-off-by: Francesco Valla <francesco.valla@mta.it>

rouge: fix partition alignment

---

moulin/builders/zephyr.py

For correct build we need to set proper environment.
Fixes: b42ac8cb54ebf8b5d9842985e1f127db47bdea0c

builders: fix `zephyr` builder

---

moulin/rouge/sfdisk.py

Add `new line` and `---` before and after debug dump of sfdisk' script to improve readability of output.

rouge: minor reformat of debug message

---

docs/rouge.rst
moulin/rouge/block_entry.py

For some cases we need to have image of certain size despite sizes of internal partitions.
This PR adds `image_size` field to image descriptor. If it is not specified or zero, then image is created taking into account internal partitions.
If actual size of partitions is bigger than `image_size` - error is raised, that we can't create image of specified size.

rouge: add possibility to specify size of image

---

docs/rouge.rst
moulin/rouge/block_entry.py
moulin/rouge/ext_utils.py

Commit adds optional `filled: zeroes` field to Empty block.
```
rpmbemul:
gpt_type: DC76DDA9-5AC1-491C-AF42-A82591580C0D # Android data
type: empty
size: 1 MiB
filled: zeroes
```
Such partitions are used by Android, like 'rpmbemul' and 'misc'.

rouge: add possibility to fill partition by zeroes

---

moulin/fetchers/repo.py
moulin/yaml_wrapper.py

This PR contains two fixing commits:
- yaml_wrapper: fix copy-paste errors in yaml_wrapper
- fetchers: fix default value for depth
The third commit is proposed for discussion because it changes the behavior of as_str(). My points are explained in the commit message and as comments inside the code.
- yaml_wrapper: allow as_str() to accept any data type

Fix repo fetcher, yaml_wrapper and rework as_str

---

docs/user-reference.rst
moulin/builders/zephyr.py

This option allows to provide custom environment variable available during build of Zephyr application.
Example of usage:
```
builder:
type: zephyr
<...>
env:
- "MY_ENV_VAR=my_value"
```
Signed-off-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>

zephyr: add `env` option to builder

---

docs/conf.py
docs/user-reference.rst
moulin/builders/yocto.py
setup.py

Since the Honister release the "_" character needs to be replaced with ":".
In particular, wrong syntax in that variable(s) being written to moulin.conf leads to the domd.bb(domu.dd):do_install tasks failure.
Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>

Update syntax for EXTERNALSRC_pn-{key}

---

docs/about.rst

Changing "is" to "it" correcting a typo

Correct typo in "About Moulin" section

---

docs/user-reference.rst

According to the documentation for `tar --auto-compress` extension `tar.bz` is not supported. So replace it with `tar.bz2`.

doc: fix file extension for `archive` builder

---

docs/conf.py
docs/user-reference.rst
moulin/builders/zephyr.py
setup.py

work_dir option allows build out-of-tree zephyr applicaton target option made optional.

add options to zephyr builder

---

docs/conf.py
docs/user-reference.rst
moulin/builders/archive.py
setup.py

This commit solves an issue that archives created by the archive builder
contain paths to files relative to build-dir. As result, paths may
contain a long list of build-related directories, and in some cases, this
is not desirable.
A possible solution is to specify desired starting point as build dir,
but this will put the resulting archive into the same directory.
So, the best way to get an archive in the top directory and get rid of
intermediate directories - is to specify the base directory for `tar`
through the `-C` option.
That's why this commit introduces the `base_dir` field for the archive
builder. The `base_dir` is an optional field, and it has '.' value if
not provided.

builders: archive: introduce tar's base dir

---

.github/workflows/python-app.yml

Default github workflow sample uses requirements.txt to install required packages, but we are using more moder approach with setup.py, so wee need to install requirements in the different way.

github workflow: install requirements from setup.py

---

moulin/rouge/block_entry.py
moulin/rouge/ext_utils.py

Fix regression from custom sector size feature -- vfat FS has to be created with correct sector size provided, otherwise it can't be mounted on running target system.

rouge: create vfat filesystem with proper sector size

---

moulin/rouge/ext_utils.py

f-strings does not work well for mkfs.vfat external ulility. E.g. on Ubuntu 22.04 these failures observed:
[..]
[INFO] Running mkfs.vfat -S 4096 /tmp/tmpysgqa_7m
mkfs.fat 4.2 (2021-01-31)
Bad logical sector size :  4096
Usage: mkfs.vfat [OPTIONS] TARGET [BLOCKS]
[..]
Neighbour code for similar cases just uses double .append(), so we'd better stick with this approach.

rouge: mkvfatfs() hotfix

---

moulin/fetchers/git.py

This commit addresses issue with git interacting with the user through the console. For example, HTTPS access to the private repo.
We use git inside the console, that is hidden from the user, so user see only hanging fetch.
So, we instruct the git to not interact with the user by the command `GIT_TERMINAL_PROMPT=0`. As result, git fails cloning and inform user that asking name/password is not possible.
This should push the user to use script-friendly authorization, like ssh.
Suggested-by: Artem Mygaiev <artem_mygaiev@epam.com>

fetchers: disable prompt usage by git

---

moulin/builders/yocto.py

```
...
common_layers: &COMMON_LAYERS
- "layer1"
- "layer2"
...
components:
comp0:
builder:
layers:
- *COMMON_LAYERS
- "layer3"
- "layer4"
```
The issue is that if an alias appears inside the 'layers' key, the
alias reaches us as an empty node without a value but with a child.
It's the same as writing:
```
layers:
-
- "nested_layer1"
- "nested_layer2"
- "layer3"
- "layer4"
```
And there is no way to step over this on the yaml level, e.g. using
some other syntax.
To make the "layers" component combinable with a variable, as in
the example above, the changes were made to the yocto.py file.
The function _flatten_layers has been added. It processes an input YAML
structure, extracting the names of individual layers as strings and
appending them to the resulting list.
The function will return: …

yocto.py: Support aliases for specifying 'layers' 

---

moulin/fetchers/git.py

Change the behavior of the git fetcher so that it doesn't apply the checkout operation again, when the repository root folder is changed manually by the user.
The git.py file has been modified. Сhanges were made to the gen_fetch function.
Previous dependency chain was:
- git_clone rule generates repository folder as an $out parameter
- git_checkout usage depends on the same repository folder
With it the change of the folder by the user leads to a side-effect, as git_checkout_stamp file marker becomes 'dirty'.
This patch changes the dependency chain to:
- git_clone rule generates repository folder AND a git_clone_stamp file marker as an $out parameter. 2 output artifacts
- git_checkout usage depends on the git_clone_stamp file marker
With this approach change of the folder by the user does …

git.py: Unlink checkout target from the repo dir

---

moulin/fetchers/git.py

Change the behavior of the git fetcher so that it doesn't consider two
or more occurrences of the same git repository in the moulin *.yaml
configuration file as an error if the duplicated repository is cloned
into different sub-folders within the build directory.
For example:
```
domd:
sources:
- type: git
url: "https://github.com/xen-troops/meta-example.git"
rev: ABCDEF
dir: "dir1"
domu:    
sources:
- type: git
url: "https://github.com/xen-troops/meta-example.git"
rev: branch_A
dir: "dir2"
```
Above, identical repositories have different branches. But, also, they
have different 'dir' parameters. So that would not be considered as an
error.
But if they would have identical directories - the error still will be
triggered.

git.py: added directory tracking to the Moulin git builder

---

moulin/builders/custom_script.py

Prior to this change "custom_script" builder ignored own source stamp, which made it impossible to use any fetchers for the build. Fix this by adding source stamps to the "deps" list.

builder: custom_script: use src_stamps as dependency

---

moulin/yaml_wrapper.py
tests/unittest/test_yaml_wrapper.py

Add tests that ensure that YamlValue and YamlDefaultValue provide the same API, and that the API is working. Fix the bugs that came up during testing.

Add tests for yaml_wrapper

---

docs/user-reference.rst
moulin/builders/zephyr.py
tests/integration_tests/zephyr_builder/test_zephyr_snippets_support/resources/zephyr_builder_with_no_snippets.yaml
tests/integration_tests/zephyr_builder/test_zephyr_snippets_support/resources/zephyr_builder_with_one_snippet.yaml
tests/integration_tests/zephyr_builder/test_zephyr_snippets_support/resources/zephyr_builder_with_snippet_and_shield.yaml
tests/integration_tests/zephyr_builder/test_zephyr_snippets_support/resources/zephyr_builder_with_two_snippets.yaml
tests/integration_tests/zephyr_builder/test_zephyr_snippets_support/test_zephyr_snippets_support.py

Zephyr 3.4.0 introduced a new feature called "snippets" which is a replacement for "shields". Add support for specifying snippets in Zephyr builder. Also, add a check to ensure that only one of "shields" or "snippets" is specified.

Add support for Zephyr snippets

---

docs/conf.py
docs/user-reference.rst
moulin/fetchers/git.py
moulin/fetchers/repo.py
setup.py

Main goal of this PR to add git submodules support.

Add submodules support for git, fix small issue with repo and bump version

---

docs/user-reference.rst
moulin/fetchers/http.py

This fetcher can be used to download files over HTTP or HTTPS protocol. Or any other protocol if it is supported by "curl" tool.

fetchers: introduce "http" fetcher

---

moulin/fetchers/http.py

Add "-L" parameter to curl invocation, so it will follow server redirects to an actual file.

fetcher: http: force CURL to follow redirects

---

docs/conf.py
setup.py

There is a new "http" fetcher added. Bump up moulin version, to moulin configs can use "min_version" to be sure that http fetcher is present.

moulin: bump version to 0.24

---

moulin/main.py

- Display default values
- Remove path to the executable
---
Original output of the script
```
$ moulin --help-config prod-devel-rcar.yaml 
usage: /home/rsm/.local/bin/moulin prod-devel-rcar.yaml
[--MACHINE {salvator-xs-m3-2x4g,salvator-xs-h3-4x2g,salvator-x-h3-4x2g,h3ulcb-4x2g,h3ulcb-4x2g-kf,h3ulcb-4x2g-ab}]
[--ENABLE_ANDROID {no,yes}] [--ENABLE_DOMU {no,yes}] [--ENABLE_ZEPHYR {no,yes}] [--ENABLE_MM {no,yes}]
[--ENABLE_AOS_VIS {no,yes}] [--GRAPHICS {binaries,sources}]
Config file description: Xen-Troops development setup for Renesas RCAR Gen3 hardware
optional arguments:
--MACHINE {salvator-xs-m3-2x4g,salvator-xs-h3-4x2g,salvator-x-h3-4x2g,h3ulcb-4x2g,h3ulcb-4x2g-kf,h3ulcb-4x2g-ab}
RCAR Gen3-based device
--ENABLE_ANDROID {no,yes}
Build Android as a guest VM
--ENABLE_DOMU {no,yes}
Build …
```

Improve the usage info

---

docs/conf.py
moulin/rouge/gpti.py
setup.py

This PR fixes issue with new `gpt-image` v 0.9.0 package, that changed its API. This issue caused the error like this:
```
gpt_image.partition.PartitionEntryError: partition overflows the last allowed Logical Block Address: 2080736 requested: 4100097
```
To fix this, we need to read another property in `Partition` object. 
Second patch bumps the moulin version, as this is quite critical fix and we need to release it ASAP

Fix issue with gpt-image

---

docs/conf.py
docs/rouge.rst
moulin/rouge/block_entry.py
moulin/rouge/gpti.py
setup.py

Hybrid MBR is kind of accepted hack, that defines (subset) of partitions both in MBR and in GPT. It is primarily used in cases when we want to use GPT, but some part of the system (like bootloader) supports only MBR. This thing is not standardized so different OSes can react differently to this it. Thus, it should be used only if there are no other options.
This patch was made with intention to be able to create Raspberry Pi Zero boot images.

rouge: add Hybrid MBR support for GPT

---

docs/conf.py
docs/rouge.rst
moulin/rouge/block_entry.py
moulin/rouge/ext_utils.py
setup.py

Add new "resize" to the raw_image block, which allows rouge to resize the raw_image to the size set in the block.
This is useful when the image size needs to be changed frequently, or multiple images need to be created from the same source files, as it allows to skip the rootfs rebuild step.
Images are copied to a temporary directory before resizing to preserve the original build artifacts. The temporary directory is created in the current working directory to prevent filling the system's /tmp with large images.

rouge: Add support for resizing raw images

---

moulin/log_utils.py
moulin/main.py

Make the log output colored depending on the log level. This will make it much easier to quickly spot errors and warnings in the output, and also looks cooler.
Control characters for colors are only added if the output is a TTY, so the output can be redirected to a file without any issues.
Here are some examples:

logs: Add colored output

---

docs/conf.py
docs/rouge.rst
moulin/rouge/block_entry.py
moulin/rouge/ext_utils.py
setup.py

This option is enabled by default for compatibility with previous
version. Also, this is sane value. But there are times, when `dd`
sparsed region detector behaves too greedy and emits un-allocated
regions even when in the original file those regions were populated
with zeroes. This is not a problem in day-to-day life, but can cause
issues when writing to un-initialized flash storages. To mitigate this
issue, `sparse` option is added to block description. This option
forces `dd` to generate un-sparsed regions, which may help in some
use-cases.

Add option to create non-spared parts of images

---

moulin/build_conf.py
tests/integration_tests/config_validator/test_check_default_true_negative/resources/test_check_default_true_negative.yaml
tests/integration_tests/config_validator/test_check_default_true_negative/test_check_default_true_negative.py
tests/integration_tests/config_validator/test_check_default_true_positive/resources/test_check_default_true_positive.yaml
tests/integration_tests/config_validator/test_check_default_true_positive/test_check_default_true_positive.py
tests/unittest/test_config.py

This change handles the case when "default: true" is not provided
for some option in the YAML file.
Now, in this scenario, a clear "YAMLProcessingError" is raised,
containing detailed and understandable information about the
misconfiguration.
Added pytests for the following scenarios:
-- YAML parameter does not contain a "default: true" variant
(negative case)
-- YAML parameter contains a "default: true" variant (positive case)
Also, the unit test "test_config.py" was updated because
"default: true" is required for all parameters in the YAML
configuration.

Provide a clear message if the default option is not specified

---

moulin/builders/yocto.py

The option `additional_deps` is part of the yocto builder, and thus applies to the whole build target, if used.
At the same time, yocto builder has to do a series of steps described as a few build targets internally.
This commit changes the creation of the build targets so that the external dependency must be satisfied before the very first build target.

yocto: change the additinal_deps handling
